In [81]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [55]:
url = 'https://en.wikipedia.org/wiki/List_of_hedge_funds'

page = requests.get(url) 

soup = BeautifulSoup(page.text,'html')

In [66]:
table = soup.find_all('table')[0]

print(table)

<table class="wikitable sortable">
<tbody><tr>
<th>Rank
</th>
<th>Firm
</th>
<th>Headquarters
</th>
<th>AUM as of June 2023<br/>(millions of USD)
</th></tr>
<tr>
<td>1
</td>
<td><a href="/wiki/Bridgewater_Associates" title="Bridgewater Associates">Bridgewater Associates</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/Westport,_Connecticut" title="Westport, Connecticut">Westport, CT</a>
</td>
<td align="center">$97,200
</td></tr>
<tr>
<td>2
</td>
<td><a href="/wiki/Man_Group" title="Man Group">Man Group</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_Kingdom" title="United Kingdom"><img alt="United Kingdom" class="mw-file-element" data-file-height="600" data-file-width="1200" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/23px-Flag_of_the_United_Kingdom.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/35px-Flag_of_the_United_Kingdom.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/46px-Flag_of_the_United_Kingdom.svg.png 2x" width="23"/></a></span></span> <a class="mw-redirect" href="/wiki/London,_UK" title="London, UK">London, UK</a>
</td>
<td align="center">$69,900
</td></tr>
<tr>
<td>3
</td>
<td><a href="/wiki/Millennium_Management,_LLC" title="Millennium Management, LLC">Millennium Management, LLC</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/New_York_City" title="New York City">New York, NY</a>
</td>
<td align="center">$57,346
</td></tr>
<tr>
<td>4
</td>
<td><a href="/wiki/The_Children%27s_Investment_Fund_Management" title="The Children's Investment Fund Management">The Children's Investment Fund Management</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_Kingdom" title="United Kingdom"><img alt="United Kingdom" class="mw-file-element" data-file-height="600" data-file-width="1200" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/23px-Flag_of_the_United_Kingdom.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/35px-Flag_of_the_United_Kingdom.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/46px-Flag_of_the_United_Kingdom.svg.png 2x" width="23"/></a></span></span> <a class="mw-redirect" href="/wiki/London,_UK" title="London, UK">London, UK</a>
</td>
<td align="center">$56,000
</td></tr>
<tr>
<td>5
</td>
<td><a href="/wiki/Citadel_LLC" title="Citadel LLC">Citadel LLC</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/Miami" title="Miami">Miami, FL</a>
</td>
<td align="center">$52,500
</td></tr>
<tr>
<td>6
</td>
<td><a href="/wiki/Elliott_Investment_Management" title="Elliott Investment Management">Elliott Investment Management</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/New_York_City" title="New York City">New York, NY</a>
</td>
<td align="center">$52,200
</td></tr>
<tr>
<td>7
</td>
<td><a href="/wiki/D._E._Shaw_%26_Co." title="D. E. Shaw &amp; Co.">D. E. Shaw &amp; Co.</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/New_York_City" title="New York City">New York, NY</a>
</td>
<td align="center">$47,740
</td></tr>
<tr>
<td>8
</td>
<td><a href="/wiki/Renaissance_Technologies" title="Renaissance Technologies">Renaissance Technologies</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/East_Setauket,_New_York" title="East Setauket, New York">East Setauket, NY</a>
</td>
<td align="center">$42,000
</td></tr>
<tr>
<td>9
</td>
<td><a href="/wiki/Two_Sigma" title="Two Sigma">Two Sigma</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/New_York_City" title="New York City">New York, NY</a>
</td>
<td align="center">$39,368
</td></tr>
<tr>
<td>10
</td>
<td><a href="/wiki/Farallon_Capital" title="Farallon Capital">Farallon Capital</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/></a></span></span> <a class="mw-redirect" href="/wiki/San_Francisco,_CA" title="San Francisco, CA">San Francisco, CA</a>
</td>
<td align="center">$39,100
</td></tr>
<tr>
<td>11
</td>
<td><a href="/wiki/Davidson_Kempner_Capital_Management" title="Davidson Kempner Capital Management">Davidson Kempner Capital Management</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/New_York_City" title="New York City">New York, NY</a>
</td>
<td align="center">$37,123
</td></tr>
<tr>
<td>12
</td>
<td><a href="/wiki/Marshall_Wace" title="Marshall Wace">Marshall Wace</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_Kingdom" title="United Kingdom"><img alt="United Kingdom" class="mw-file-element" data-file-height="600" data-file-width="1200" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/23px-Flag_of_the_United_Kingdom.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/35px-Flag_of_the_United_Kingdom.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/46px-Flag_of_the_United_Kingdom.svg.png 2x" width="23"/></a></span></span> <a class="mw-redirect" href="/wiki/London,_UK" title="London, UK">London, UK</a>
</td>
<td align="center">$34,665
</td></tr>
<tr>
<td>13
</td>
<td><a href="/wiki/Brevan_Howard" title="Brevan Howard">Brevan Howard</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_Kingdom" title="United Kingdom"><img alt="United Kingdom" class="mw-file-element" data-file-height="600" data-file-width="1200" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/23px-Flag_of_the_United_Kingdom.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/35px-Flag_of_the_United_Kingdom.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/46px-Flag_of_the_United_Kingdom.svg.png 2x" width="23"/></a></span></span> <a class="mw-redirect" href="/wiki/London,_UK" title="London, UK">London, UK</a>
</td>
<td align="center">$32,900
</td></tr>
<tr>
<td>14
</td>
<td><a href="/wiki/Ruffer_Investment_Company" title="Ruffer Investment Company">Ruffer</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_Kingdom" title="United Kingdom"><img alt="United Kingdom" class="mw-file-element" data-file-height="600" data-file-width="1200" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/23px-Flag_of_the_United_Kingdom.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/35px-Flag_of_the_United_Kingdom.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/46px-Flag_of_the_United_Kingdom.svg.png 2x" width="23"/></a></span></span> <a class="mw-redirect" href="/wiki/London,_UK" title="London, UK">London, UK</a>
</td>
<td align="center">$31,313
</td></tr>
<tr>
<td>15
</td>
<td><a href="/wiki/Point72_Asset_Management" title="Point72 Asset Management">Point72 Asset Management</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/Stamford,_Connecticut" title="Stamford, Connecticut">Stamford, CT</a>
</td>
<td align="center">$30,600
</td></tr>
<tr>
<td>16
</td>
<td><a href="/wiki/AQR_Capital" title="AQR Capital">AQR Capital</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/Greenwich,_Connecticut" title="Greenwich, Connecticut">Greenwich, CT</a>
</td>
<td align="center">$29,700
</td></tr>
<tr>
<td>17
</td>
<td><a href="/wiki/Anchorage_Capital_Group" title="Anchorage Capital Group">Anchorage Capital Group</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/New_York_City" title="New York City">New York, NY</a>
</td>
<td align="center">$27,300
</td></tr>
<tr>
<td>18
</td>
<td><a href="/wiki/Capula_Investment_Management" title="Capula Investment Management">Capula Investment Management</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_Kingdom" title="United Kingdom"><img alt="United Kingdom" class="mw-file-element" data-file-height="600" data-file-width="1200" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/23px-Flag_of_the_United_Kingdom.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/35px-Flag_of_the_United_Kingdom.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/46px-Flag_of_the_United_Kingdom.svg.png 2x" width="23"/></a></span></span> <a class="mw-redirect" href="/wiki/London,_UK" title="London, UK">London, UK</a>
</td>
<td align="center">$26,900
</td></tr>
<tr>
<td>19
</td>
<td><a href="/wiki/PIMCO" title="PIMCO">PIMCO</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/></a></span></span> <a href="/wiki/Newport_Beach,_California" title="Newport Beach, California">Newport Beach, CA</a>
</td>
<td align="center">$25,619
</td></tr>
<tr>
<td>20
</td>
<td><a href="/wiki/Baupost_Group" title="Baupost Group">Baupost Group</a>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/></a></span></span> <a class="mw-redirect" href="/wiki/Boston,_MA" title="Boston, MA">Boston, MA</a>
</td>
<td align="center">$23,879
</td></tr></tbody></table>

In [77]:
titles = table.find_all('th')

In [78]:
titles

[<th>Rank
 </th>,
 <th>Firm
 </th>,
 <th>Headquarters
 </th>,
 <th>AUM as of June 2023<br/>(millions of USD)
 </th>]

In [79]:
table_titles = [title.text.strip() for title in titles]

print(table_titles)

['Rank', 'Firm', 'Headquarters', 'AUM as of June 2023(millions of USD)']

In [82]:
df= pd.DataFrame(columns=table_titles)

In [83]:
df

Empty DataFrame
Columns: [Rank, Firm, Headquarters, AUM as of June 2023(millions of USD)]
Index: []

In [85]:
columns = table.find_all('tr')

In [91]:
for row in columns[1:]:
    rows = row.find_all('td')
    each_row_data = [data.text.strip() for data in rows]
    
    length = len(df)
    df.loc[length] = each_row_data

In [92]:
df

,Rank,Firm,Headquarters,AUM as of June 2023(millions of USD)
0,1,Bridgewater Associates,"Westport, CT","$97,200"
1,2,Man Group,"London, UK","$69,900"
2,3,"Millennium Management, LLC","New York, NY","$57,346"
3,4,The Children's Investment Fund Management,"London, UK","$56,000"
4,5,Citadel LLC,"Miami, FL","$52,500"
5,6,Elliott Investment Management,"New York, NY","$52,200"
6,7,D. E. Shaw & Co.,"New York, NY","$47,740"
7,8,Renaissance Technologies,"East Setauket, NY","$42,000"
8,9,Two Sigma,"New York, NY","$39,368"
9,10,Farallon Capital,"San Francisco, CA","$39,100"
10,11,Davidson Kempner Capital Management,"New York, NY","$37,123"
11,12,Marshall Wace,"London, UK","$34,665"
12,13,Brevan Howard,"London, UK","$32,900"
13,14,Ruffer,"London, UK","$31,313"
14,15,Point72 Asset Management,"Stamford, CT","$30,600"
15,16,AQR Capital,"Greenwich, CT","$29,700"
16,17,Anchorage Capital Group,"New York, NY","$27,300"
17,18,Capula Investment Management,"London, UK","$26,900"
18,19,PIMCO,"Newport Beach, CA","$25,619"
19,20,Baupost Group,"Boston, MA","$23,879"

In [94]:
df.to_csv(r'C:\Users\user\Desktop\VS workspaces\Data Scraping 1\Hedge_Funds.csv', index = False )